version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ryspglit4h95"
s3_prefix = "test-lambda"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
